// src/db/seed-utils.ts
import { sql } from 'drizzle-orm';
import { getTableConfig } from 'drizzle-orm/sqlite-core';
import * as schema from './schema.ts';

export const MOCK_PRODUCTS = [
  // Computers
  {
    title: 'Quantum Pro Laptop',
    desc: 'High-performance laptop for professionals with 32GB RAM.',
    categoryName: 'Computers',
    price: 1499.99,
    image: 'https://loremflickr.com/400/400/laptop',
  },
  {
    title: 'Desktop Workstation X',
    desc: 'Tower PC optimized for 3D rendering and heavy workloads.',
    categoryName: 'Computers',
    price: 2499.0,
    image: 'https://loremflickr.com/400/400/workstation',
  },
  {
    title: 'UltraWide Monitor 34',
    desc: 'Curved 34-inch display with 144Hz refresh rate.',
    categoryName: 'Computers',
    price: 599.5,
    image: 'https://loremflickr.com/400/400/monitor',
  },
  {
    title: 'Mechanical Keyboard',
    desc: 'Tactile mechanical keyboard with customizable RGB.',
    categoryName: 'Computers',
    price: 129.99,
    image: 'https://loremflickr.com/400/400/keyboard',
  },
  {
    title: 'Wireless Ergonomic Mouse',
    desc: 'Vertical mouse designed to prevent wrist strain.',
    categoryName: 'Computers',
    price: 59.9,
    image: 'https://loremflickr.com/400/400/mouse',
  },
  {
    title: 'NVMe SSD 2TB',
    desc: 'Ultra-fast PCIe Gen4 storage for gaming and productivity.',
    categoryName: 'Computers',
    price: 159.99,
    image: 'https://loremflickr.com/400/400/ssd',
  },
  {
    title: 'Compact Mini PC',
    desc: 'Space-saving desktop perfect for home offices.',
    categoryName: 'Computers',
    price: 450.0,
    image: 'https://loremflickr.com/400/400/pc',
  },
  {
    title: 'USB-C Docking Station',
    desc: "Expand your laptop's connectivity with dual HDMI and 4 USB ports.",
    categoryName: 'Computers',
    price: 89.99,
    image: 'https://loremflickr.com/400/400/dockingstation',
  },
  {
    title: '4K Web Camera',
    desc: 'Crystal clear video calls with auto-focus and built-in mic.',
    categoryName: 'Computers',
    price: 119.5,
    image: 'https://loremflickr.com/400/400/webcam',
  },
  {
    title: '32GB DDR5 RAM Kit',
    desc: 'Next-gen memory for lightning-fast multitasking.',
    categoryName: 'Computers',
    price: 135.0,
    image: 'https://loremflickr.com/400/400/ram',
  },
  {
    title: 'Dual Monitor Arm',
    desc: 'Fully adjustable desk mount for two 27-inch screens.',
    categoryName: 'Computers',
    price: 75.99,
    image: 'https://loremflickr.com/400/400/desksetup',
  },
  {
    title: 'High-Airflow PC Case',
    desc: 'Mid-tower case with tempered glass and 4 RGB fans.',
    categoryName: 'Computers',
    price: 110.0,
    image: 'https://loremflickr.com/400/400/pccase',
  },

  // Games
  {
    title: 'Elden Ring: Definitive',
    desc: 'Epic open-world fantasy action RPG.',
    categoryName: 'Games',
    price: 69.99,
    image: 'https://loremflickr.com/400/400/fantasygame',
  },
  {
    title: 'Cyber City 2089',
    desc: 'Sci-fi adventure game with immersive graphics.',
    categoryName: 'Games',
    price: 59.99,
    image: 'https://loremflickr.com/400/400/cyberpunk',
  },
  {
    title: 'Cozy Farm Simulator',
    desc: 'Relaxing farming and life simulation game.',
    categoryName: 'Games',
    price: 29.99,
    image: 'https://loremflickr.com/400/400/farmgame',
  },
  {
    title: 'Galactic Racer',
    desc: 'High-speed zero-gravity racing.',
    categoryName: 'Games',
    price: 39.99,
    image: 'https://loremflickr.com/400/400/spaceship',
  },
  {
    title: 'Mystery Mansion',
    desc: 'Co-op puzzle and survival horror.',
    categoryName: 'Games',
    price: 24.99,
    image: 'https://loremflickr.com/400/400/mansion',
  },
  {
    title: 'Retro Arcade Collection',
    desc: '30 classic arcade games in one bundle.',
    categoryName: 'Games',
    price: 19.99,
    image: 'https://loremflickr.com/400/400/arcade',
  },
  {
    title: 'Fantasy RPG VIII',
    desc: 'A sprawling saga of magic, crystals, and rebellion.',
    categoryName: 'Games',
    price: 49.99,
    image: 'https://loremflickr.com/400/400/rpg',
  },
  {
    title: 'Tactical Shooter Pro',
    desc: 'Competitive 5v5 multiplayer tactical FPS.',
    categoryName: 'Games',
    price: 34.99,
    image: 'https://loremflickr.com/400/400/shooter',
  },
  {
    title: 'Super Platformer Bros',
    desc: 'Classic jump-and-run action for all ages.',
    categoryName: 'Games',
    price: 49.99,
    image: 'https://loremflickr.com/400/400/platformer',
  },
  {
    title: 'Grand Strategy World',
    desc: 'Conquer continents and build your empire from scratch.',
    categoryName: 'Games',
    price: 59.99,
    image: 'https://loremflickr.com/400/400/strategygame',
  },
  {
    title: 'Fighting Tournament 5',
    desc: 'Next-gen 2D fighting game with a massive roster.',
    categoryName: 'Games',
    price: 59.99,
    image: 'https://loremflickr.com/400/400/fightinggame',
  },
  {
    title: 'VR Beat Rhythm',
    desc: 'Slice blocks to the beat of adrenaline-pumping music.',
    categoryName: 'Games',
    price: 29.99,
    image: 'https://loremflickr.com/400/400/vr',
  },

  // Books
  {
    title: 'The Pragmatic Programmer',
    desc: 'Your journey to mastery in software engineering.',
    categoryName: 'Books',
    price: 45.0,
    image: 'https://loremflickr.com/400/400/programmingbook',
  },
  {
    title: 'Sci-Fi Anthology',
    desc: 'A collection of short stories from the future.',
    categoryName: 'Books',
    price: 18.5,
    image: 'https://loremflickr.com/400/400/scifibook',
  },
  {
    title: 'Cooking for Beginners',
    desc: '100 easy recipes for everyday meals.',
    categoryName: 'Books',
    price: 22.99,
    image: 'https://loremflickr.com/400/400/cookbook',
  },
  {
    title: 'History of the Ancient World',
    desc: 'A deep dive into ancient civilizations.',
    categoryName: 'Books',
    price: 35.0,
    image: 'https://loremflickr.com/400/400/historybook',
  },
  {
    title: 'The Art of War',
    desc: 'Classic treatise on strategy and tactics.',
    categoryName: 'Books',
    price: 12.99,
    image: 'https://loremflickr.com/400/400/strategybook',
  },
  {
    title: 'Data-Intensive Applications',
    desc: 'The definitive guide to distributed systems.',
    categoryName: 'Books',
    price: 49.95,
    image: 'https://loremflickr.com/400/400/databasebook',
  },
  {
    title: 'Fantasy Epic: Book One',
    desc: 'The beginning of a legendary trilogy.',
    categoryName: 'Books',
    price: 24.99,
    image: 'https://loremflickr.com/400/400/fantasybook',
  },
  {
    title: 'Modern Web Development',
    desc: 'Mastering React, TypeScript, and full-stack architecture.',
    categoryName: 'Books',
    price: 39.99,
    image: 'https://loremflickr.com/400/400/webdevbook',
  },
  {
    title: 'The Psychology of Money',
    desc: 'Timeless lessons on wealth, greed, and happiness.',
    categoryName: 'Books',
    price: 19.99,
    image: 'https://loremflickr.com/400/400/financebook',
  },
  {
    title: 'Mystery of the Old Manor',
    desc: 'A thrilling whodunit that will keep you guessing.',
    categoryName: 'Books',
    price: 16.5,
    image: 'https://loremflickr.com/400/400/mysterybook',
  },
  {
    title: 'Learn Python in 30 Days',
    desc: 'A step-by-step crash course for beginners.',
    categoryName: 'Books',
    price: 29.99,
    image: 'https://loremflickr.com/400/400/pythonbook',
  },
  {
    title: 'Atomic Habits',
    desc: 'An easy and proven way to build good habits.',
    categoryName: 'Books',
    price: 21.0,
    image: 'https://loremflickr.com/400/400/habitsbook',
  },

  // Clothing
  {
    title: 'Classic Cotton T-Shirt',
    desc: '100% organic cotton, breathable and soft.',
    categoryName: 'Clothing',
    price: 19.99,
    image: 'https://loremflickr.com/400/400/tshirt',
  },
  {
    title: 'Vintage Denim Jacket',
    desc: 'Timeless blue denim jacket with brass buttons.',
    categoryName: 'Clothing',
    price: 89.5,
    image: 'https://loremflickr.com/400/400/denimjacket',
  },
  {
    title: 'Running Sneakers',
    desc: 'Lightweight shoes with maximum shock absorption.',
    categoryName: 'Clothing',
    price: 119.99,
    image: 'https://loremflickr.com/400/400/sneakers',
  },
  {
    title: 'Wool Winter Beanie',
    desc: 'Keep warm with this knitted merino wool beanie.',
    categoryName: 'Clothing',
    price: 24.0,
    image: 'https://loremflickr.com/400/400/beanie',
  },
  {
    title: 'Waterproof Hiking Jacket',
    desc: 'Breathable rain jacket for outdoor adventures.',
    categoryName: 'Clothing',
    price: 149.95,
    image: 'https://loremflickr.com/400/400/hikingjacket',
  },
  {
    title: 'Athletic Sweatpants',
    desc: 'Comfortable joggers for workouts or lounging.',
    categoryName: 'Clothing',
    price: 45.0,
    image: 'https://loremflickr.com/400/400/sweatpants',
  },
  {
    title: 'Cashmere Crewneck Sweater',
    desc: 'Luxuriously soft and warm for chilly evenings.',
    categoryName: 'Clothing',
    price: 129.0,
    image: 'https://loremflickr.com/400/400/sweater',
  },
  {
    title: 'Casual Chino Pants',
    desc: 'Versatile trousers suitable for work or weekend wear.',
    categoryName: 'Clothing',
    price: 55.0,
    image: 'https://loremflickr.com/400/400/chinos',
  },
  {
    title: 'Summer Flowy Dress',
    desc: 'Lightweight floral dress perfect for hot days.',
    categoryName: 'Clothing',
    price: 65.99,
    image: 'https://loremflickr.com/400/400/dress',
  },
  {
    title: 'Leather Ankle Boots',
    desc: 'Durable and stylish boots with a slight heel.',
    categoryName: 'Clothing',
    price: 135.0,
    image: 'https://loremflickr.com/400/400/boots',
  },
  {
    title: 'Graphic Print Hoodie',
    desc: 'Cozy fleece pullover with a retro design.',
    categoryName: 'Clothing',
    price: 59.99,
    image: 'https://loremflickr.com/400/400/hoodie',
  },
  {
    title: 'Polarized Sunglasses',
    desc: 'UV400 protection with a classic aviator frame.',
    categoryName: 'Clothing',
    price: 85.0,
    image: 'https://loremflickr.com/400/400/sunglasses',
  },

  // Electronics
  {
    title: 'Noise-Cancelling Headphones',
    desc: 'Over-ear wireless headphones with ANC.',
    categoryName: 'Electronics',
    price: 299.99,
    image: 'https://loremflickr.com/400/400/headphones',
  },
  {
    title: 'Smartphone Pro Max',
    desc: 'Latest flagship phone with an incredible camera.',
    categoryName: 'Electronics',
    price: 1199.0,
    image: 'https://loremflickr.com/400/400/smartphone',
  },
  {
    title: 'Smart Home Hub',
    desc: 'Control all your connected devices from one screen.',
    categoryName: 'Electronics',
    price: 99.99,
    image: 'https://loremflickr.com/400/400/smarthome',
  },
  {
    title: 'Bluetooth Speaker',
    desc: 'Portable waterproof speaker with deep bass.',
    categoryName: 'Electronics',
    price: 79.5,
    image: 'https://loremflickr.com/400/400/speaker',
  },
  {
    title: '4K Action Camera',
    desc: 'Rugged camera for recording extreme sports.',
    categoryName: 'Electronics',
    price: 349.99,
    image: 'https://loremflickr.com/400/400/actioncamera',
  },
  {
    title: 'Fitness Tracker Watch',
    desc: 'Monitor heart rate, sleep, and daily steps.',
    categoryName: 'Electronics',
    price: 149.0,
    image: 'https://loremflickr.com/400/400/smartwatch',
  },
  {
    title: '65-inch OLED TV',
    desc: 'Stunning 4K resolution with infinite contrast.',
    categoryName: 'Electronics',
    price: 1799.99,
    image: 'https://loremflickr.com/400/400/tv',
  },
  {
    title: 'Smart Thermostat',
    desc: "Save energy by intelligently managing your home's climate.",
    categoryName: 'Electronics',
    price: 199.0,
    image: 'https://loremflickr.com/400/400/thermostat',
  },
  {
    title: 'Wireless Charging Pad',
    desc: 'Fast-charge your phone and earbuds simultaneously.',
    categoryName: 'Electronics',
    price: 39.99,
    image: 'https://loremflickr.com/400/400/wirelesscharger',
  },
  {
    title: 'E-Reader Paper Display',
    desc: 'Glare-free screen that reads like real paper.',
    categoryName: 'Electronics',
    price: 129.99,
    image: 'https://loremflickr.com/400/400/ereader',
  },
  {
    title: 'Drone with 4K Camera',
    desc: 'Capture breathtaking aerial footage with ease.',
    categoryName: 'Electronics',
    price: 499.0,
    image: 'https://loremflickr.com/400/400/drone',
  },
  {
    title: 'Portable Power Bank 20000mAh',
    desc: 'Charge your devices multiple times on the go.',
    categoryName: 'Electronics',
    price: 49.99,
    image: 'https://loremflickr.com/400/400/powerbank',
  },
  {
    title: 'Extended Gaming Mousepad',
    desc: 'Large desk mat with anti-slip rubber base and stitched edges.',
    categoryName: 'Computers',
    price: 19.99,
    image: 'https://loremflickr.com/400/400/mousepad',
  },
  {
    title: 'Cat6 Ethernet Cable 50ft',
    desc: 'High-speed gigabit network cable for stable connections.',
    categoryName: 'Computers',
    price: 14.5,
    image: 'https://loremflickr.com/400/400/ethernet',
  },
  {
    title: 'GeForce RTX 4080 Graphics Card',
    desc: 'Next-generation GPU for ultimate 4K gaming performance.',
    categoryName: 'Computers',
    price: 1199.99,
    image: 'https://loremflickr.com/400/400/gpu',
  },
  {
    title: '850W Gold Power Supply',
    desc: 'Fully modular ATX power supply with high efficiency.',
    categoryName: 'Computers',
    price: 129.0,
    image: 'https://loremflickr.com/400/400/powersupply',
  },
  {
    title: 'Liquid CPU Cooler 240mm',
    desc: 'All-in-one water cooling system with customizable RGB pump.',
    categoryName: 'Computers',
    price: 89.99,
    image: 'https://loremflickr.com/400/400/cpu_cooler',
  },
  {
    title: 'Adjustable Aluminum Laptop Stand',
    desc: 'Ergonomic riser compatible with 10-15.6 inch laptops.',
    categoryName: 'Computers',
    price: 24.99,
    image: 'https://loremflickr.com/400/400/laptopstand',
  },
  {
    title: '256GB USB 3.2 Flash Drive',
    desc: 'Ultra-compact thumb drive with fast read/write speeds.',
    categoryName: 'Computers',
    price: 22.5,
    image: 'https://loremflickr.com/400/400/flashdrive',
  },
  {
    title: 'Professional Graphic Drawing Tablet',
    desc: 'Large active area with battery-free stylus and 8192 pressure levels.',
    categoryName: 'Computers',
    price: 65.0,
    image: 'https://loremflickr.com/400/400/drawingtablet',
  },
  {
    title: 'WiFi 6 Tri-Band Router',
    desc: 'Gigabit wireless internet router for large homes and gaming.',
    categoryName: 'Computers',
    price: 199.99,
    image: 'https://loremflickr.com/400/400/router',
  },
  {
    title: 'External 1080p Capture Card',
    desc: 'Record and stream gameplay directly to your PC with zero latency.',
    categoryName: 'Computers',
    price: 110.0,
    image: 'https://loremflickr.com/400/400/capturecard',
  },

  // Games
  {
    title: 'Settlers of the Realm Board Game',
    desc: 'Strategic resource management and trading board game.',
    categoryName: 'Games',
    price: 45.0,
    image: 'https://loremflickr.com/400/400/boardgame',
  },
  {
    title: 'Force Feedback Racing Wheel',
    desc: 'Realistic steering wheel and pedal set for racing simulators.',
    categoryName: 'Games',
    price: 249.99,
    image: 'https://loremflickr.com/400/400/racingwheel',
  },
  {
    title: 'Tournament Arcade Stick',
    desc: 'Premium fight stick with Sanwa parts for fighting game enthusiasts.',
    categoryName: 'Games',
    price: 159.5,
    image: 'https://loremflickr.com/400/400/arcadestick',
  },
  {
    title: 'Virtual Reality Headset Pro',
    desc: 'Standalone VR headset with immersive 3D spatial audio.',
    categoryName: 'Games',
    price: 399.0,
    image: 'https://loremflickr.com/400/400/vrheadset',
  },
  {
    title: 'Mind Bender Puzzle Quest',
    desc: 'A challenging puzzle game that tests your logic and spatial awareness.',
    categoryName: 'Games',
    price: 14.99,
    image: 'https://loremflickr.com/400/400/puzzle',
  },
  {
    title: 'Pixel Knight Odyssey',
    desc: 'Award-winning indie platformer with a beautiful retro aesthetic.',
    categoryName: 'Games',
    price: 19.99,
    image: 'https://loremflickr.com/400/400/pixelgame',
  },
  {
    title: 'Dragon Chronicles: Awakening',
    desc: 'Massive JRPG with turn-based combat and a sweeping narrative.',
    categoryName: 'Games',
    price: 59.99,
    image: 'https://loremflickr.com/400/400/jrpg',
  },
  {
    title: 'MMO 60-Day Time Card',
    desc: 'Prepaid subscription card for the most popular fantasy MMO.',
    categoryName: 'Games',
    price: 29.99,
    image: 'https://loremflickr.com/400/400/gamecard',
  },
  {
    title: 'Rhythm Dancer 2026',
    desc: 'Dance to the latest hits with full body tracking compatibility.',
    categoryName: 'Games',
    price: 49.99,
    image: 'https://loremflickr.com/400/400/dancegame',
  },
  {
    title: 'Aero Flight Simulator',
    desc: 'Incredibly detailed civilian aviation simulator covering the entire globe.',
    categoryName: 'Games',
    price: 69.99,
    image: 'https://loremflickr.com/400/400/flightsimulator',
  },

  // Books
  {
    title: 'Steve Jobs: A Biography',
    desc: 'The exclusive biography of Apple’s visionary co-founder.',
    categoryName: 'Books',
    price: 18.0,
    image: 'https://loremflickr.com/400/400/biography',
  },
  {
    title: 'The Silent Patient',
    desc: 'A gripping psychological thriller that will keep you on the edge of your seat.',
    categoryName: 'Books',
    price: 14.5,
    image: 'https://loremflickr.com/400/400/thrillerbook',
  },
  {
    title: 'Selected Poems of Robert Frost',
    desc: 'A comprehensive collection of America’s most beloved poet.',
    categoryName: 'Books',
    price: 11.99,
    image: 'https://loremflickr.com/400/400/poetry',
  },
  {
    title: 'Watchmen Graphic Novel',
    desc: 'The groundbreaking comic that redefined the superhero genre.',
    categoryName: 'Books',
    price: 24.99,
    image: 'https://loremflickr.com/400/400/graphicnovel',
  },
  {
    title: 'Oxford English Dictionary',
    desc: 'The definitive record of the English language.',
    categoryName: 'Books',
    price: 35.0,
    image: 'https://loremflickr.com/400/400/dictionary',
  },
  {
    title: 'Where the Wild Things Are',
    desc: 'A classic illustrated children’s book about imagination.',
    categoryName: 'Books',
    price: 8.99,
    image: 'https://loremflickr.com/400/400/childrensbook',
  },
  {
    title: 'Japan Travel Guide 2026',
    desc: 'Essential tips, maps, and itineraries for your trip to Japan.',
    categoryName: 'Books',
    price: 22.5,
    image: 'https://loremflickr.com/400/400/travelguide',
  },
  {
    title: 'Meditations by Marcus Aurelius',
    desc: 'Timeless stoic philosophy from a Roman Emperor.',
    categoryName: 'Books',
    price: 9.99,
    image: 'https://loremflickr.com/400/400/philosophy',
  },
  {
    title: 'The Story of Art',
    desc: 'An accessible and engaging introduction to art history.',
    categoryName: 'Books',
    price: 45.0,
    image: 'https://loremflickr.com/400/400/artbook',
  },
  {
    title: 'How to Win Friends and Influence People',
    desc: 'The fundamental guide to effective communication and leadership.',
    categoryName: 'Books',
    price: 15.99,
    image: 'https://loremflickr.com/400/400/selfhelp',
  },

  // Clothing
  {
    title: 'Merino Wool Hiking Socks (3-Pack)',
    desc: 'Moisture-wicking, blister-preventing socks for long trails.',
    categoryName: 'Clothing',
    price: 24.0,
    image: 'https://loremflickr.com/400/400/socks',
  },
  {
    title: 'Silk Geometric Necktie',
    desc: 'Elegant 100% silk tie perfect for formal occasions.',
    categoryName: 'Clothing',
    price: 29.99,
    image: 'https://loremflickr.com/400/400/necktie',
  },
  {
    title: 'Full Grain Leather Belt',
    desc: 'Durable and classic brown leather belt with a brass buckle.',
    categoryName: 'Clothing',
    price: 35.0,
    image: 'https://loremflickr.com/400/400/belt',
  },
  {
    title: 'Plaid Cashmere Scarf',
    desc: 'Incredibly soft and warm scarf for cold winter days.',
    categoryName: 'Clothing',
    price: 45.5,
    image: 'https://loremflickr.com/400/400/scarf',
  },
  {
    title: 'Touchscreen Leather Gloves',
    desc: 'Keep your hands warm while using your smartphone.',
    categoryName: 'Clothing',
    price: 39.99,
    image: 'https://loremflickr.com/400/400/gloves',
  },
  {
    title: 'Insulated Winter Parka',
    desc: 'Heavy-duty winter coat with a faux-fur lined hood.',
    categoryName: 'Clothing',
    price: 189.0,
    image: 'https://loremflickr.com/400/400/wintercoat',
  },
  {
    title: 'One-Piece Sport Swimsuit',
    desc: 'Chlorine-resistant swimwear designed for active swimming.',
    categoryName: 'Clothing',
    price: 42.0,
    image: 'https://loremflickr.com/400/400/swimsuit',
  },
  {
    title: 'Cotton Flannel Pajama Set',
    desc: 'Cozy two-piece sleepwear set in a classic plaid pattern.',
    categoryName: 'Clothing',
    price: 34.99,
    image: 'https://loremflickr.com/400/400/pajamas',
  },
  {
    title: 'Cargo Shorts with Pockets',
    desc: 'Durable cotton shorts with multiple utility pockets.',
    categoryName: 'Clothing',
    price: 28.5,
    image: 'https://loremflickr.com/400/400/shorts',
  },
  {
    title: 'Embroidered Baseball Cap',
    desc: 'Adjustable cotton cap to keep the sun out of your eyes.',
    categoryName: 'Clothing',
    price: 18.0,
    image: 'https://loremflickr.com/400/400/cap',
  },

  // Electronics
  {
    title: 'Surge Protector Power Strip',
    desc: '8 outlets with 3 USB charging ports and a 6-foot cord.',
    categoryName: 'Electronics',
    price: 22.99,
    image: 'https://loremflickr.com/400/400/powerstrip',
  },
  {
    title: '8K HDMI Cable 10ft',
    desc: 'Ultra High Speed HDMI 2.1 cable supporting 48Gbps bandwidth.',
    categoryName: 'Electronics',
    price: 15.99,
    image: 'https://loremflickr.com/400/400/hdmicable',
  },
  {
    title: 'True Wireless Earbuds',
    desc: 'Bluetooth 5.3 earbuds with touch controls and charging case.',
    categoryName: 'Electronics',
    price: 49.99,
    image: 'https://loremflickr.com/400/400/earbuds',
  },
  {
    title: 'Mini Portable Home Projector',
    desc: '1080p supported LED projector for movie nights and gaming.',
    categoryName: 'Electronics',
    price: 89.0,
    image: 'https://loremflickr.com/400/400/projector',
  },
  {
    title: '50mm f/1.8 Prime Camera Lens',
    desc: 'Great low-light lens perfect for portrait photography.',
    categoryName: 'Electronics',
    price: 199.0,
    image: 'https://loremflickr.com/400/400/cameralens',
  },
  {
    title: 'Adjustable Camera Tripod',
    desc: 'Lightweight aluminum tripod with a 3-way pan head.',
    categoryName: 'Electronics',
    price: 34.5,
    image: 'https://loremflickr.com/400/400/tripod',
  },
  {
    title: 'Smart LED Light Bulb (2-Pack)',
    desc: 'Color-changing WiFi bulbs compatible with voice assistants.',
    categoryName: 'Electronics',
    price: 24.99,
    image: 'https://loremflickr.com/400/400/smartbulb',
  },
  {
    title: 'USB Condenser Microphone',
    desc: 'Studio-quality mic for podcasting, streaming, and voiceovers.',
    categoryName: 'Electronics',
    price: 55.0,
    image: 'https://loremflickr.com/400/400/microphone',
  },
  {
    title: '128GB MicroSDXC Card',
    desc: 'High-speed memory card for cameras, phones, and consoles.',
    categoryName: 'Electronics',
    price: 18.99,
    image: 'https://loremflickr.com/400/400/sdcard',
  },
  {
    title: 'Universal Battery Charger',
    desc: 'Smart charger for AA, AAA, C, and D rechargeable batteries.',
    categoryName: 'Electronics',
    price: 21.0,
    image: 'https://loremflickr.com/400/400/batterycharger',
  },

  // Home & Kitchen
  {
    title: 'Programmable Drip Coffee Maker',
    desc: '12-cup coffee machine with a timer and keep-warm function.',
    categoryName: 'Home & Kitchen',
    price: 45.0,
    image: 'https://loremflickr.com/400/400/coffeemaker',
  },
  {
    title: 'High-Speed Blender',
    desc: 'Powerful 1000W blender for smoothies, soups, and crushing ice.',
    categoryName: 'Home & Kitchen',
    price: 89.99,
    image: 'https://loremflickr.com/400/400/blender',
  },
  {
    title: '4-Slice Stainless Steel Toaster',
    desc: 'Extra-wide slots with bagel and defrost settings.',
    categoryName: 'Home & Kitchen',
    price: 39.5,
    image: 'https://loremflickr.com/400/400/toaster',
  },
  {
    title: '15-Piece Kitchen Knife Block Set',
    desc: 'High-carbon stainless steel knives with a wooden storage block.',
    categoryName: 'Home & Kitchen',
    price: 75.0,
    image: 'https://loremflickr.com/400/400/knifeset',
  },
  {
    title: 'Bamboo Cutting Board Set',
    desc: 'Set of 3 organic bamboo boards for chopping meat and veggies.',
    categoryName: 'Home & Kitchen',
    price: 24.99,
    image: 'https://loremflickr.com/400/400/cuttingboard',
  },
  {
    title: 'Non-Stick Frying Pan 10-inch',
    desc: 'Scratch-resistant skillet suitable for all stovetops.',
    categoryName: 'Home & Kitchen',
    price: 29.99,
    image: 'https://loremflickr.com/400/400/fryingpan',
  },
  {
    title: 'Cordless Stick Vacuum Cleaner',
    desc: 'Lightweight vacuum with powerful suction for hard floors and carpets.',
    categoryName: 'Home & Kitchen',
    price: 149.0,
    image: 'https://loremflickr.com/400/400/vacuum',
  },
  {
    title: 'Egyptian Cotton Sheet Set (Queen)',
    desc: 'Ultra-soft 600 thread count bed sheets.',
    categoryName: 'Home & Kitchen',
    price: 65.0,
    image: 'https://loremflickr.com/400/400/bedsheets',
  },
  {
    title: 'Plush Bath Towel Set (6-Piece)',
    desc: 'Highly absorbent and quick-drying 100% cotton towels.',
    categoryName: 'Home & Kitchen',
    price: 42.5,
    image: 'https://loremflickr.com/400/400/towels',
  },
  {
    title: 'LED Desk Lamp with Wireless Charger',
    desc: 'Dimmable reading lamp with an integrated phone charging base.',
    categoryName: 'Home & Kitchen',
    price: 35.99,
    image: 'https://loremflickr.com/400/400/desklamp',
  },

  // Sports & Outdoors
  {
    title: 'Non-Slip Yoga Mat',
    desc: 'Eco-friendly 6mm thick exercise mat with a carrying strap.',
    categoryName: 'Sports & Outdoors',
    price: 28.0,
    image: 'https://loremflickr.com/400/400/yogamat',
  },
  {
    title: 'Adjustable Dumbbell Set',
    desc: 'Space-saving weights that adjust from 5 to 52.5 lbs each.',
    categoryName: 'Sports & Outdoors',
    price: 199.0,
    image: 'https://loremflickr.com/400/400/dumbbells',
  },
  {
    title: 'Speed Jump Rope',
    desc: 'Tangle-free skipping rope with ball bearings for fitness training.',
    categoryName: 'Sports & Outdoors',
    price: 12.99,
    image: 'https://loremflickr.com/400/400/jumprope',
  },
  {
    title: '4-Person Pop-Up Camping Tent',
    desc: 'Water-resistant family tent that sets up in 60 seconds.',
    categoryName: 'Sports & Outdoors',
    price: 110.0,
    image: 'https://loremflickr.com/400/400/tent',
  },
  {
    title: 'Mummy Sleeping Bag',
    desc: 'Cold-weather sleeping bag rated for temperatures down to 15°F.',
    categoryName: 'Sports & Outdoors',
    price: 55.5,
    image: 'https://loremflickr.com/400/400/sleepingbag',
  },
  {
    title: 'Insulated Stainless Steel Water Bottle',
    desc: 'Keeps drinks cold for 24 hours or hot for 12 hours.',
    categoryName: 'Sports & Outdoors',
    price: 24.99,
    image: 'https://loremflickr.com/400/400/waterbottle',
  },
  {
    title: 'Official Size Leather Football',
    desc: 'Durable composite leather ball for practice and games.',
    categoryName: 'Sports & Outdoors',
    price: 32.0,
    image: 'https://loremflickr.com/400/400/football',
  },
  {
    title: 'Adult Tennis Racket',
    desc: 'Lightweight and powerful racket for beginner to intermediate players.',
    categoryName: 'Sports & Outdoors',
    price: 65.0,
    image: 'https://loremflickr.com/400/400/tennisracket',
  },
  {
    title: 'Aerodynamic Bicycle Helmet',
    desc: 'Ventilated safety helmet with a dial fit adjustment system.',
    categoryName: 'Sports & Outdoors',
    price: 45.99,
    image: 'https://loremflickr.com/400/400/bikehelmet',
  },
  {
    title: 'Men’s Waterproof Hiking Boots',
    desc: 'Rugged trail boots with ankle support and high-traction soles.',
    categoryName: 'Sports & Outdoors',
    price: 89.95,
    image: 'https://loremflickr.com/400/400/hikingboots',
  },

  // Health & Beauty
  {
    title: 'Argan Oil Shampoo and Conditioner',
    desc: 'Sulfate-free set that moisturizes and repairs damaged hair.',
    categoryName: 'Health & Beauty',
    price: 29.99,
    image: 'https://loremflickr.com/400/400/shampoo',
  },
  {
    title: 'Eau de Parfum Spray 3.4 oz',
    desc: 'A luxurious floral fragrance with notes of jasmine and rose.',
    categoryName: 'Health & Beauty',
    price: 85.0,
    image: 'https://loremflickr.com/400/400/perfume',
  },
  {
    title: 'Gentle Foaming Face Wash',
    desc: 'Daily cleanser that removes dirt and makeup without drying.',
    categoryName: 'Health & Beauty',
    price: 14.5,
    image: 'https://loremflickr.com/400/400/facewash',
  },
  {
    title: 'Hyaluronic Acid Moisturizer',
    desc: 'Lightweight daily cream that locks in hydration for glowing skin.',
    categoryName: 'Health & Beauty',
    price: 22.0,
    image: 'https://loremflickr.com/400/400/moisturizer',
  },
  {
    title: 'Electric Sonic Toothbrush',
    desc: 'Rechargeable toothbrush with 5 brushing modes and a smart timer.',
    categoryName: 'Health & Beauty',
    price: 49.99,
    image: 'https://loremflickr.com/400/400/toothbrush',
  },
  {
    title: 'Ionic Hair Dryer',
    desc: 'Professional blow dryer that reduces frizz and cuts drying time.',
    categoryName: 'Health & Beauty',
    price: 55.0,
    image: 'https://loremflickr.com/400/400/hairdryer',
  },
  {
    title: 'Broad Spectrum Mineral Sunscreen SPF 50',
    desc: 'Reef-safe, water-resistant sun protection for face and body.',
    categoryName: 'Health & Beauty',
    price: 18.99,
    image: 'https://loremflickr.com/400/400/sunscreen',
  },
  {
    title: '18-Color Eyeshadow Palette',
    desc: 'Highly pigmented matte and shimmer shades for any look.',
    categoryName: 'Health & Beauty',
    price: 26.5,
    image: 'https://loremflickr.com/400/400/makeup',
  },
  {
    title: 'Vitamin C Brightening Serum',
    desc: 'Anti-aging facial serum that evens skin tone and reduces wrinkles.',
    categoryName: 'Health & Beauty',
    price: 34.0,
    image: 'https://loremflickr.com/400/400/serum',
  },
  {
    title: 'Classic Safety Razor Shaving Kit',
    desc: 'Includes a double-edge razor, shaving brush, and stand.',
    categoryName: 'Health & Beauty',
    price: 42.0,
    image: 'https://loremflickr.com/400/400/shavingkit',
  },

  // Toys
  {
    title: 'Space Exploration Building Blocks Set',
    desc: '800-piece rocket ship and launch pad building kit.',
    categoryName: 'Toys',
    price: 59.99,
    image: 'https://loremflickr.com/400/400/legoset',
  },
  {
    title: 'Superhero Action Figure',
    desc: '12-inch posable figure with detailed armor and accessories.',
    categoryName: 'Toys',
    price: 19.99,
    image: 'https://loremflickr.com/400/400/actionfigure',
  },
  {
    title: 'Fashion Doll with Wardrobe',
    desc: 'Includes doll, three outfits, and styling accessories.',
    categoryName: 'Toys',
    price: 24.5,
    image: 'https://loremflickr.com/400/400/doll',
  },
  {
    title: '1000-Piece Landscape Jigsaw Puzzle',
    desc: 'Beautiful mountain and lake scenery for hours of relaxation.',
    categoryName: 'Toys',
    price: 16.99,
    image: 'https://loremflickr.com/400/400/jigsawpuzzle',
  },
  {
    title: 'High-Speed Remote Control Car',
    desc: 'Off-road RC truck capable of reaching 25 mph.',
    categoryName: 'Toys',
    price: 45.0,
    image: 'https://loremflickr.com/400/400/rccar',
  },
  {
    title: 'Professional Aluminum Yo-Yo',
    desc: 'Unresponsive yo-yo designed for advanced string tricks.',
    categoryName: 'Toys',
    price: 22.0,
    image: 'https://loremflickr.com/400/400/yoyo',
  },
  {
    title: 'Large Rainbow Delta Kite',
    desc: 'Easy-to-fly kite suitable for kids and adults at the beach.',
    categoryName: 'Toys',
    price: 15.5,
    image: 'https://loremflickr.com/400/400/kite',
  },
  {
    title: 'Pump-Action Water Blaster',
    desc: 'High-capacity water gun that shoots up to 30 feet.',
    categoryName: 'Toys',
    price: 18.0,
    image: 'https://loremflickr.com/400/400/watergun',
  },
  {
    title: 'Giant Plush Teddy Bear',
    desc: 'Super soft and cuddly 36-inch stuffed animal.',
    categoryName: 'Toys',
    price: 39.99,
    image: 'https://loremflickr.com/400/400/teddybear',
  },
  {
    title: 'Speed Rubik’s Cube',
    desc: 'Stickerless 3x3 puzzle cube engineered for fast turning.',
    categoryName: 'Toys',
    price: 12.5,
    image: 'https://loremflickr.com/400/400/rubikscube',
  },

  // Tools & Home Improvement
  {
    title: '16 oz Fiberglass Claw Hammer',
    desc: 'Durable hammer with an ergonomic shock-absorbing grip.',
    categoryName: 'Tools',
    price: 18.5,
    image: 'https://loremflickr.com/400/400/hammer',
  },
  {
    title: 'Magnetic Screwdriver Set (42-Piece)',
    desc: 'Includes flathead, phillips, and torx bits with a carrying case.',
    categoryName: 'Tools',
    price: 24.99,
    image: 'https://loremflickr.com/400/400/screwdrivers',
  },
  {
    title: '20V Cordless Power Drill',
    desc: 'Compact drill/driver kit with battery, charger, and bit set.',
    categoryName: 'Tools',
    price: 65.0,
    image: 'https://loremflickr.com/400/400/powerdrill',
  },
  {
    title: '25-Foot Tape Measure',
    desc: 'Heavy-duty measuring tape with a fraction-read blade.',
    categoryName: 'Tools',
    price: 12.99,
    image: 'https://loremflickr.com/400/400/tapemeasure',
  },
  {
    title: 'Adjustable Wrench Set (4-Piece)',
    desc: 'Drop-forged steel wrenches ranging from 6 to 12 inches.',
    categoryName: 'Tools',
    price: 29.5,
    image: 'https://loremflickr.com/400/400/wrenchset',
  },
  {
    title: 'Heavy-Duty Duct Tape (3-Pack)',
    desc: 'Industrial strength silver tape for repairs and bundling.',
    categoryName: 'Tools',
    price: 14.0,
    image: 'https://loremflickr.com/400/400/ducttape',
  },
  {
    title: 'Professional Paintbrush Set (5-Piece)',
    desc: 'Synthetic bristle brushes for smooth finishes on trim and walls.',
    categoryName: 'Tools',
    price: 19.99,
    image: 'https://loremflickr.com/400/400/paintbrushes',
  },
  {
    title: '3-Step Folding Step Ladder',
    desc: 'Sturdy steel stool with wide, anti-slip rubber pedals.',
    categoryName: 'Tools',
    price: 45.0,
    image: 'https://loremflickr.com/400/400/stepladder',
  },
  {
    title: 'Tactical LED Flashlight',
    desc: 'Super bright 1000 lumen flashlight with zoomable focus.',
    categoryName: 'Tools',
    price: 21.5,
    image: 'https://loremflickr.com/400/400/flashlight',
  },
  {
    title: 'Anti-Fog Safety Goggles',
    desc: 'Wrap-around protective eyewear for DIY projects and construction.',
    categoryName: 'Tools',
    price: 11.99,
    image: 'https://loremflickr.com/400/400/safetygoggles',
  },
].toSorted(() => Math.random() - 0.5);

export async function resetDatabase(db: any) {
  for (const key of Object.keys(schema)) {
    const table = (schema as any)[key];
    if (table && typeof table === 'object' && 'id' in table) {
      const { name } = getTableConfig(table);
      await db.run(sql.raw(`DELETE FROM ${name}`));
      await db.run(sql.raw(`DELETE FROM sqlite_sequence WHERE name='${name}'`));
    }
  }
}

export async function seedDatabase(db: any) {
  const BATCH_SIZE = 10;

  const categoriesToInsert = [
    'Computers',
    'Games',
    'Books',
    'Clothing',
    'Electronics',
    'Toys',
    'Tools',
    'Health & Beauty',
    'Sports & Outdoors',
    'Home & Kitchen',
  ].map((c) => ({ designation: c }));

  const insertedCategories = await db
    .insert(schema.productsCategories)
    .values(categoriesToInsert)
    .returning();

  const categoryMap = Object.fromEntries(
    insertedCategories.map((c: any) => [c.designation, c.id])
  );

  const productsToInsert = MOCK_PRODUCTS.map((product, i) => {
    const stableRating = Number.parseFloat((((i * 1.3) % 4) + 1).toFixed(1));
    const stableCount = (i * 123) % 5000;

    return {
      title: product.title,
      description: product.desc,
      image: product.image,
      price: product.price,
      categoryId: categoryMap[product.categoryName],
      ratingRate: stableRating,
      ratingCount: stableCount,
    };
  });

  for (let i = 0; i < productsToInsert.length; i += BATCH_SIZE) {
    const batch = productsToInsert.slice(i, i + BATCH_SIZE);
    await db.insert(schema.products).values(batch);
  }
}
