info:
  name: Products category path param
  type: http
  seq: 3

http:
  method: GET
  url: https://rest-assured.stephan-ullmann.workers.dev/products/category/:category?maxPrice=30
  params:
    - name: maxPrice
      value: "30"
      type: query
    - name: page
      value: "1"
      type: query
      disabled: true
    - name: limit
      value: "2"
      type: query
      disabled: true
    - name: query
      value: phone
      type: query
      disabled: true
    - name: category
      value: book
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
